title: "Igor Katrayev"
description: "Personal site / CV"
# Use a supported theme for GitHub Pages
# See https://pages.github.com/themes/
theme: minima

# Set baseurl empty since site is served from the repository root via Pages
baseurl: ""
url: "https://ikatraev.github.io"

# Navigation links (minima)
minima:
  social_links:
    - { platform: github, user_url: "https://github.com/ikatraev" }

# Build settings
markdown: kramdown
kramdown:
  input: GFM

plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Exclude development files if any
exclude:
  - vendor
  - README.md
